model_list:
  - model_name: Gemini 2.0 Flash Experimental
    litellm_params:
      model: gemini/gemini-2.0-flash-exp
      api_key: os.environ/GOOGLE_AI_API_KEY # runs os.getenv("GOOGLE_AI_API_KEY=")
  - model_name: Llama 3.1 70b instruct
    litellm_params:
      model: openrouter/meta-llama/llama-3.1-70b-instruct:free  # add openai/ prefix to route as OpenAI provider
      api_key: os.environ/OPENROUTER_API_KEY # api key to send your model
  - model_name: Phi 3 mini 4k Instruct
    litellm_params:
      model: huggingface/microsoft/Phi-3-mini-4k-instruct
      api_key: os.environ/HUGGINGFACE_API_KEY